name:  wrk_deployToHuggingFace

on:
  push:
    branches:
      - demo_huggingFace

jobs:
  deployment:
    runs-on:  ubuntu-latest
    steps:
      -name:  stp_checkout_latest
        uses: actions/checkout@latest_demo
      - name: stp_setup_python
        uses: actions/setup-python@v2
        with:
          python-version:  "3.8.16"
      - name: stp_install_deps
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: stp_build_metadata_file
        run:  |
          python build_metadata_file.py
      - name: stp_commit_metadata_file
        run:  |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add metadata-*
          git commit -m "add metadata file"
      - name: stp_push_to_hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/kidcoconut/spc_healthcareClaimAnomalies demo
