name:  wrk_deployToHuggingFace

on:
  push:
    branches: [demo_huggingFace]

  #--- allow to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on:  ubuntu-latest
    environment:  env_huggingFace
    steps:
      - run: echo "INFO - start job ... "
      #--- action:  checkout the code from the branch;  only a single commit by default
      - name:  stp_checkout_latest
        uses: actions/checkout@v3
        with:
          #--- default repo:  ${{ github.repository }}
          repository: ''
          ref:  demo_huggingFace
      - run: |
          git status
          pwd
          #--- echo "INFO - checked out repo/branch - ${{ github.repository }} / ${{ github.ref_name }} "
      #--- 
      - name: stp_machine_pwd1;  show dir contents pre-mods
        working-directory : "."
        run: |
          echo "INFO:  get dir listing1"
          pwd
          ls -la .
          ls -ls ./demo/app
      #--- set git config args;  set username and email to the person who performed the last commit to the branch
      - name:  stp_init_git_config
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      #--- create a branch for deploy to main;  ready for push to huggingface
      - name:  stp_prep_for_deploy
        run: |
          #git checkout -b deploy_huggingface
          git checkout -b main
          rm README.md bootstrap*
          git mv demo/app/* .
          rm -r demo
          git commit -am "ready to deploy to huggingface"
      #--- 
      - name: stp_machine_pwd2;  show dir contents post-mods
        working-directory : "."
        run: |
          echo "INFO:  get dir listing2"
          pwd
          ls -la .
      #--- 
      - name:  stp_push_to_hugging_face;  push local demo_huggingFace to remote main branch
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: kidcoconut
          SPACE_NAME: spc_healthcareClaimAnomalies
        run: |
          #git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME deploy_huggingFace:main 
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main 
      #--- 
      #---
      - name: stp_push_to_hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/kidcoconut/spc_healthcareClaimAnomalies demo
