name:  wrk_deployToHuggingFace2

on:
  push:
    branches: [demo_huggingFace]

  #--- allow to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on:  ubuntu-latest
    environment:  env_huggingFace
    steps:
      #---
      - name:  stp_start_job
        run: |
          echo "INFO - start job ... "
          pwd
          ls -la .
          #ls -la ..
          
      #--- action:  checkout the code from the branch;  only a single commit by default
      - name:  stp_checkout_latest
        uses: actions/checkout@v3
        with:
          #--- default repo:  ${{ github.repository }}
          repository: ''
          ref:  demo_huggingFace
          
      #---
      - name:  stp_gitStatus_rpoGitHub
        run: |
          #--- echo "INFO - checked out repo/branch - ${{ github.repository }} / ${{ github.ref_name }} "
          pwd
          echo "INFO:  list remotes ..."
          git remote -v
          
          echo "INFO:  rename remotes ..."
          git remote rename origin gitHub
          
          git status
          
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
          ls -la
          
      #---
      - name:  stp_gitStatus_rpoHuggingFace
        run: |
          cd ..
          echo "INFO:  checking current working dir ... "
          pwd
          ls -la
          
      #--- 
      - name:  stp_clone_from_hugging_face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: kidcoconut
          SPACE_NAME: spc_healthcareClaimAnomalies
        run: |
          #echo "INFO:  checking current working dir ... "
          #pwd
          cd ..         #--- Note:  code appears to run in parallel;  we need to move up to parent folder so repos are beside one another
          #ls -la
          pwd
          echo "INFO:  cloning from huggingFace ... "
          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          echo "INFO:  moving into the repo directory ... "
          cd $SPACE_NAME
          echo "INFO:  checking current working dir ... "
          pwd
          ls -la
          
      #--- 
      - name:  stp_upd_remotes_huggingFace
        env:
          SPACE_NAME: spc_healthcareClaimAnomalies
        run: |          
          cd ..
          pwd
          cd $SPACE_NAME
          echo "INFO:  list remotes ..."
          git remote -v
          echo "INFO:  rename remotes ..."
          git remote rename origin hugFace
      
      
      #--- set git config args;  set username and email to the person who performed the last commit to the branch
      #- name:  stp_init_git_config
      #  run: |
      #    git config user.name "$(git log -n 1 --pretty=format:%an)"
      #    git config user.email "$(git log -n 1 --pretty=format:%ae)"
      
      
      #--- 
      - name:  stp_merge_gitHubBranchFiles_to_huggingFace
        run: |
          #cd ..
          pwd
          cp -r ../rpo_mleHealthcareClaimAnomalies/demo/app/* .
          echo "INFO:  git status ..."
          ls -la
          
          git status      #--- should be in main
          git commit -am "merged github/demo_huggingFace into runner/main"


      #---
      #- name:  stp_switch to a different branch
      #  run: |
      #    git checkout -b deploy_huggingFace
      #    git rm -r *
          
          
      #--- 
      #- name: stp_runner_pwd1;  show dir contents pre-mods
      #  run: |
      #    echo "INFO:  get dir listing1"
      #    pwd
      #    ls -la .
      #    ls -ls ./demo/app


      #--- create a branch for deploy to main;  ready for push to huggingface
      #- name:  stp_prep_for_deploy
      #  run: |
      #    rm README.md bootstrap*
      #    git mv demo/app/* .
      #    rm -r demo
      #    git commit -am "cleaned up working folder, ready for deploy to huggingFace"
          
      #--- 
      #- name: stp_machine_pwd2;  show dir contents post-mods
      #  working-directory : "."
      #  run: |
      #    echo "INFO:  get dir listing2"
      #    pwd
      #    ls -la .
          
      #--- 
      - name:  stp_push_to_hugging_face;  push local demo_huggingFace to remote main branch
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: kidcoconut
          SPACE_NAME: spc_healthcareClaimAnomalies
        run: |
          pwd
          #git checkout main
          #git merge --no-edit deploy_huggingFace
          git push -f hugFace main 
